- templates/boot/grub/addons.cfg
- templates/boot/isolinux/addon_27_netboot.cfg
Added configuration for isolinux and grub to add a menu entry to boot
netboot.xyz. The actual netboot.xyz.lkrn needs to be part of
grml-live-addons to make this work, see PR #8 in grml-live-grml:
grml/grml-live-grml#8
> Added support for netboot.xyz

- etc/grml/fai/config/files/etc/systemd/system-preset/10-grml.preset/GRMLBASE
- etc/grml/fai/config/scripts/GRMLBASE/15-initsetup
To enabled or disable services on boot-time we should use systemd.presets. This change implements the effort of `15-initsetup` in `/etc/systemd/system/system-preset/10-grml.preset`.
And: There is also a "minor" fix where `fcopy` did not set ownership/permission correctly when copying `/etc/systemd`.
> Enable and disable services by using systemd.presets

- etc/grml/fai/config/files/etc/systemd/system-preset/10-grml.preset/GRMLBASE
- etc/grml/fai/config/scripts/GRMLBASE/15-initsetup
We decided to disable all services by default and only enable the ones
we really need. Currently only getty, grml-autoconfig and the
debug-shell are enabled.
> Use systemd.preset to disable all unneeded services

- grml-live
Most security-conscious users expect to find SHA-256 hashes of files, since both MD5 and SHA-1 are considered weak.  SHA-512 additionally has the benefit that it is significantly faster than SHA-256 on 64-bit systems, processing twice as much data per chunk with only 125% of the operations.  Generate both SHA-256 and SHA-512 hashes anywhere we provide SHA-1 hashes.
> Add SHA-256 and SHA-512 hashes

- etc/grml/fai/config/files/etc/systemd/system/grml-boot.target/GRMLBASE
- etc/grml/fai/config/files/etc/systemd/system/ssh-bootoption.service/GRMLBASE
- etc/grml/fai/config/scripts/GRMLBASE/15-initsetup
With this new target we can now define which services are started on
boot.
Prior this target some services (without a systemd-service file) were
automatically started because of the systemd-sysv-generator (i.e.
ser2net).
Thanks: Felipe Sateler
Closes grml/release-planning#2 @ GH
> Provide new grml-boot.target

- etc/grml/fai/config/files/etc/apt/sources.list.d/debian.list/DEBIAN_STABLE
I assume that Debian stable should track Stretch in grml-live so then we need to track stretch-backports instead of jessie-backports for the DEBIAN_STABLE apt source file.
> Use stretch-backports instead of jessie-backports for stable

- templates/GRML/grml-cheatcodes.txt
And while doing so change links to manpage to publicly available manpage
links, because the links to the manpage source is barely readable.
Closes: grml/grml-live#57
> Update broken links

- debian/control
When running grml-live with genisoimage (9:1.1.11-3+b2) on Debian/stretch the
following error is shown:
```
[...]
[*] Finished execution of stage 'squashfs'
[*] Forcing rebuild of ISO because files on ISO have been modified.
[*] Using genisoimage to build ISO.
genisoimage: -i option no longer supported.
stat: cannot stat '/dev/shm/grml-live/grml_isos/grml_0.0.1.iso': No such file or directory
[!] Error: there was a critical error executing stage 'iso build
```
Closes: grml/grml-live#65
> Remove genisoimage from dependencies

- templates/GRML/grml-cheatcodes.txt
While debugging grml/grml#61, it was unclear for me what the expected
behavior should be. Grml defaults to LOCAL (in /etc/adjtime) which
means that Hardware Clock is expected to be set in local time (which is
usually the case on Windows only systems).
The time zone defaults to UTC.
> Update cheatcodes to clarify hardware clock and timezone defaults

- etc/grml/fai/config/package_config/GRML_FULL
add `tree` and `ncdu` to `GRML_FULL`. IMHO they are quite useful and donot consume much space (might be candidates for `GRML_SMALL` as well?!).
> Additional software

- etc/grml/fai/config/package_config/GRMLBASE
*cryptsetup in initramfs* has been moved to a [separate package](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=cryptsetup-initramfs), instead of setting `CRYPTSETUP=y` for the default initramfs scripts, since current stable debian *buster*. This is necessary to boot *grml* with `persistence-encryption=luks` as described [here](https://wiki.grml.org/doku.php?id=persistency).
> SW: cryptsetup-initramfs (fix persistence-encryption)

- templates/boot/grub/%SHORT_NAME%_options.cfg
- templates/boot/isolinux/grml.cfg
Grml should use Predictable Network Interface Names by default.
To make that switch easier we added a new boot options "pnet".
The kernel command line options "net.ifnames=0" is currently in every
boot option (except "pnet") but should be removed when Predictable
Network Interface Names works for us.
See: grml/grml#127
> Add boot option pnet (Predictable Network Interface Names)

- templates/boot/grub/%SHORT_NAME%_default.cfg
- templates/boot/grub/%SHORT_NAME%_options.cfg
kernelopts are used by grml-rescueboot to communicate kernel arguments from the host's grub to the grub within the grml ISO. E.g., the host grub boot entry will contains something like:
````
kernelopts=" arg1 arg2 blacklist=foo etc "
export kernelopts
````
Currently, grub within the grml ISO will pass this entire string as one single argument to the kernel. Remove the quotes such that the arguments are interpreted as intended.
Fixes https://github.com/grml/grml-rescueboot/issues/5
> GRUB: remove erroneous quotes around kernelopts

- templates/boot/grub/addons.cfg
Looks like a relic from the bad, old days.
It's certainly not needed any longer, since the initrd16 command can
load the file just fine and newer grub versions are not able to load
compressed files in such a manner, since the length (+2880) refers to
the uncompressed size. Grub will see that the file is smaller than that
and error out. If we were to give it the compressed size, decompression
would fail due to the buffer being too small.
> GRUB: drop loopback usage for balder10/FreeDOS.

- docs/grml-live.txt
- etc/grml/grml-live.conf
While isolinux's "manifold" mode was used by default a long time ago,
Grml switched to the isohybrid method in late 2011, mostly due to manifold
being incompatible with UEFI systems.
Documentation and configuration files weren't updated at that time,
though.
Do it now.
> grml-live: isohybrid is the default, reflect that.

- templates/GRML/grml-cheatcodes.txt
This modifies `grml-cheatcodes.txt` to include the changes in grml/live-boot-grml#13 and clarifies that the device description is fully optional.
> Update fromiso documentation

- grml-live
Won't actually cause harm, but a spurious empty directory in the resulting squashfs root image looks weird.
> grml-live: clean up MIRROR_DIRECTORY if provided.

- docs/grml-live.txt
Explain that the output dir shouldn't be nodev, noexec or nosuid (some packages may fail to configure correctly with nosuid even if no problems are immediately apparent with the default builds).
Add information on how to find errors in FAI logs.
Improve the section on reverting manifold.
> grml-live.txt: output dir mount options; errors; manifold

- etc/grml/fai/config/grml/squashfs-excludes
- etc/grml/fai/config/package_config/ZFS
- etc/grml/fai/config/scripts/GRMLBASE/18-timesetup
These files and directories are created by dkms while it builds modules on
demand and are only relevant during the module build/installation process.
The .ko files are then installed in /lib/modules; shipping /var/lib/dkms/*
inside the squashfs only takes up space without providing a tangible
benefit.
> Exclude /var/lib/dkms/* from squashfs

- etc/grml/fai/config/hooks/instsoft.ZFS
- etc/grml/fai/config/package_config/ZFS
The `ZFS` FAI class will, via the `instsoft.ZFS` hook, install the packages
needed to build the zfs modules, build the zfs modules, then remove the
development packages again to avoid bloating the ISO. The ZFS
`package_config` now only installs `zfsutils-linux` so that the iso contains
the userspace zfs tools.
In my tests, the ZFS class now only increases the size of the ISO by about
3MB.
I wanted to rely on apt autoremove to get rid of automatically installed
packages, but for some reason as of 2.5.2 autoremove doesn't actually remove
some of the development packages (e.g. gcc-11) even though they're Priority
optional, marked as auto-installed, and not depended on by anything that
isn't auto-installed.
So, to avoid bloating the ISO with hundreds of MB of development packages,
the …
> Add support for building grml ISOs with zfs

- etc/grml/fai/config/files/etc/initramfs-tools/modules/GRMLBASE
- etc/grml/fai/config/scripts/GRMLBASE/80-initramfs
As of kmod v30+20220905-1 (as present in current Debian/bookworm), the output of the "modprobe --all --set-version="..." --ignore-install --quiet --show-depends nfs" command line, as used by initramfs-tools to identify dependencies of the the nfs module, changed. See https://bugs.debian.org/1022172 for further details.
Until the situation between kmod, /lib/modprobe.d/50-nfs.conf and initramfs-tools has been resolved, let's provide a workaround, so our initramfs includes the required modules for netboot usage with NFS.
Thanks: András Korn
Closes: https://github.com/grml/grml/issues/192
> Provide workaround for kmod/initramfs-tools issue with NFS/netboot

- etc/grml/fai/config/files/etc/systemd/system/getty@tty1.service.d/override.conf/GRMLBASE
The SHELL variable is not set in our tty1 when `run-welcome` is called (instead of agetty(8) + login(1)).
So, when invoking `screen` we end up in `/bin/sh` instead of a zsh shell.
We also had the same problem for tty2 - tty4 and fixed it in grml/grml-live@6871972 (to fix grml/grml#14).
We now use the same approach to fix tty1 although the SHELL variable should (most probably) be set in `run-welcome` and `run-screen` itself.
Issue: grml/grml#135
> Set SHELL variable in tty1

- grml-live
Now as of git commit 721a473 the disk usage of the Secure Boot files increased and 4MB are no longer enough. We don't support Secure Boot for i386, so when either building for i386 or amd64 without Secure Boot then keep the default 4MB size. But if Secure Boot is not disabled and when not building for i386 (:= amd64) then increase EFI size to 8MB.
Thanks: János Pásztor for bugreport and initial patch
> Increase EFI image size when using Secure Boot on amd64

- templates/GRML/grml-cheatcodes.txt
One can use bootfrom=/dev/disk/by-label/yourlabel or also isofrom=/dev/disk/by-label/yourlabel to avoid choosing the wrong block device.
We dropped the tohd feature back in 2016 (see grml-autoconfig commit 0fb27bae), so drop it while at it.
Thanks: Csillag Tamas
> grml-cheatcodes.txt: document usage of bootfrom=/dev/disk/by-label* + drop deprecated tohd

- etc/grml/fai/config/package_config/GRML_FULL
- etc/grml/fai/config/package_config/GRML_SMALL
Disk space requirements:
* lolcat on grml-small: ~28.5 MB of additional disk space
* toilet on grml-small: ~1800 kB of additional disk space
-> so let's only add toilet to GRML_SMALL
* lolcat on grml-full:  ~152 kB of additional disk space
* toilet on grml-full: ~1800 kB of additional disk space
-> it's about 2MB of additional disk space for GRML_FULL in total,
so we can add both lolcat and toilet without too much overhead
> SW: add toilet to GRML_SMALL + GRML_FULL and lolcat to GRML_FULL

- templates/boot/grub/%SHORT_NAME%_options.cfg
- templates/boot/isolinux/grml.cfg
The boot order and the naming of the isolinux boot menu and Grub boot menu were not in sync. I tried to standardize the boot menu entries, according to the proposal in
https://github.com/grml/grml/issues/10#issuecomment-1625729783
Related: grml/grml#10
> Unify boot options order

- etc/grml/fai/config/files/usr/share/doc/grml-docs/startpage.html/GRMLBASE
- templates/boot/isolinux/f10
Re `grml-docs/startpage.html`:
* We don't ship xlinks2, so drop it from the browser list
* Iceweasel no longer exists
* There's no point in providing usage instructions for the command line browsers, other than how to exit them (if someone really ends up there without being used to w3/links)
* Replace all references to http with https
* Let's drop tldp.org / Linux Documentation Project (unsure whether this is relevant for anyone nowadays?), and instead link to Grml Wiki
* We moved our IRC from freenode to oftc, update accordingly
* While at it, misc rewordings and section adjustments, to reduce text on page
And in `templates/boot/isolinux/f10` I stumbled upon references to freenode
> grml-docs/startpage.html + templates/boot/isolinux/f10: rework and update instructions

- etc/grml/fai/config/files/etc/fstab/GRMLBASE
Usage of IP addresses like 1.2.3.4 is not recommended, as they might point to actually used and non-reserved IPs.
Quoting from RFC 5737 AKA "IPv4 Address Blocks Reserved for Documentation" (see https://datatracker.ietf.org/doc/html/rfc5737):
```
| The blocks 192.0.2.0/24 (TEST-NET-1), 198.51.100.0/24 (TEST-NET-2), and
| 203.0.113.0/24 (TEST-NET-3) are provided for use in documentation.
```
So use 192.0.2.42 instead.
> etc/fstab/GRMLBASE: use reserved IP following RFC5737

- docs/grml-live.txt
By default `apt-get update` fails on recent Debian releases (also see apt-secure(8), if the chain of trust hasn't been established yet:
```
| # apt-get update
| Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB] | Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB] | Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB] | Get:4 http://deb.grml.org grml-stable InRelease [8382 B] | Get:5 http://deb.grml.org grml-testing InRelease [15.1 kB] | Get:6 http://deb.debian.org/debian bookworm/main amd64 Packages [8786 kB] | Err:4 http://deb.grml.org grml-stable InRelease
|   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 21E0CA38EA2EA4AB
| Get:7 http://deb.debian.org/debian …
```
> docs: update usage instructions for setting up Grml repository

- etc/grml/fai/config/package_config/GRML_FULL
The package is missing in Debian/testing due to `hfsutils: ftbfs with GCC-14` (see https://bugs.debian.org/1075067).
HFS dates pack to 1985 and as of Mac OS 10.6 Apple dropped support for writing HFS. Since Mac OS 10.15 HFS also can't be read anymore.
Given that HFS shouldn't be really relevant for Grml users those days, let's drop it from our package list.
> SW: drop hfsutils (unavailable in Debian/testing and deprecated filesystem)

- etc/grml/fai/config/package_config/GRML_FULL
Debian will drop the package, see
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1078247
> SW: drop reiser4progs (to be removed from Debian)

- debian/grml-live.maintscript
- etc/grml/fai/config/files/etc/apt/sources.list.d/debian.list/DEBIAN_SID
- grml-live
On our recent grml64-full sid/unstable daily ISOs we ended up with udhcpc (the busybox DHCP client implementation) instead of dhcpcd.
We build our daily ISOs with grml-live, using `-s sid -c DEBORPHAN,GRMLBASE,GRML_FULL,RELEASE,AMD64,IGNORE`. The class selection then gets mapped to FAI classes `DEBIAN_SID DEBORPHAN GRMLBASE GRML_FULL RELEASE AMD64 IGNORE`.
For handling the isc-dhcp-client/dhcpcd situation, we need to enable its according DEBIAN_* class (as we can handle this only for releases newer than bookworm, as cloud-init had a hard dependency on isc-dhcp-client up until and including bookworm, see https://bugs.debian.org/1051421 for details).
So in /etc/grml/fai/config/package_config/DEBIAN_UNSTABLE we already handle the isc-dhcp-client -> dhcpcd switch for unstable, but now that we …
> Fix DHCP situation with grml-full unstable/sid

- etc/grml/fai/config/package_config/GRMLBASE
Quoting from https://github.com/jirka-h/haveged/blob/master/README.md:
```
Starting from Linux kernel v5.4, the HAVEGED inspired algorithm has been
included in the Linux kernel (see the LKML article and the Linux Kernel
commit). Additionally, since v5.6, as soon as the CRNG (the Linux
cryptographic-strength random number generator) gets ready, /dev/random
does not block on reads anymore (see this commit).
```
Given that even oldstable AKA bullseye is at kernel version 5.10, let's give it a try to run our live systems without haveged by default.
> SW: drop haveged from GRMLBASE

- debian/rules
Otherwise executing `fakeroot debian/rules clean` leaves plenty of files around.
> debian/rules: get rid of build files in clean target

- templates/boot/isolinux/f3
Used the same order as the "Isolinux bootprompt options" in grml-cheatcodes.txt.
Relates to: grml/grml#9
> Adjust the order of the isolinux f3 help splash

- templates/GRML/grml-cheatcodes.txt
- templates/boot/isolinux/hidden.cfg
grml-autoconfig dropped this, as it is broken under systemd and nobody seems to be using it.
See https://github.com/grml/grml-autoconfig/pull/17
> Drop debian2hd boot option

- etc/grml/fai/config/scripts/GRMLBASE/03-get-sources
- grml-live
Necessary for building in (unprivileged) docker, where bind mounts are not allowed.
> SOURCES: move directory instead of bind-mounting it in

- etc/grml/fai/config/scripts/GRMLBASE/03-get-sources
Saves about 8min (~40%!) on a GRML_SMALL build.
Also calls apt-get less often, as we now ask dpkg for the source package names.
> SOURCES: run apt-get source parallelized

- etc/grml/fai/config/package_config/GRML_FULL
As brought up by bremner on IRC, useful for usage on airgapped systems, only requires 549 kB of additional disk space.
> SW: add scdaemon to GRML_FULL

- etc/grml/fai/config/hooks/instsoft.GRMLBASE
- etc/grml/fai/config/hooks/updatebase.GRMLBASE
`updatebase.GRMLBASE` mounts various special filesystems. This fails in Docker, where mounting filesystems (even existing ones) does not work.
Half of the mounts were already guarded with `|| true`. Guard the others too, so they can be skipped.
> Fix BUILD_ONLY mode inside Docker

- etc/grml/fai/config/package_config/GRML_FULL
- grml-live
- remaster/grml-live-remaster
Since 3c0d23bcd80c75ab4390d467f3bfceed42bce0c7 (from 2018!) grml-live hard-depended on `xorriso`. Remove leftover genisoimage/mkisofs support.
Also drop genisoimage from `GRML_FULL`, which already must include `xorriso` (for grml-live).
> Drop vestigial genisoimage/mkisofs support

- etc/grml/fai/config/package_config/DEBIAN_TESTING
- etc/grml/fai/config/package_config/DEBIAN_TRIXIE
- etc/grml/fai/config/package_config/DEBIAN_UNSTABLE
The dhcpcd package provides the files /etc/init.d/dhcpcd, /usr/lib/systemd/system/dhcpcd.service +
/usr/lib/systemd/system/dhcpcd@.service, neither of which we depend on. We also don't start any of those services with our Grml live systems via systemd presets.
Also cloud-init only depends on dhcpcd-base, so let's depend on dhcpcd-base with Debian trixie and newer.
Thanks to @jkirk for raising this.
Closes: grml/grml-live#187
> SW: replace dhcpcd with dhcpcd-base in DEBIAN_*

- grml-live
These previously said "64-bit", which is not wrong, but it can now mean arm64 too.
> grml-live: update EFI image messages

- build-driver/build.py
Useful for local testing. In CI, this directory never exists, but when running the build scripts locally it is usually left over from a previous run.
> build-driver: allow basefiles directory to already exist

- etc/grml/fai/config/package_config/GRML_FULL
- etc/grml/fai/config/package_config/GRML_SMALL
Will probably go away in the Debian trixie release.
> GRML_FULL, GRML_SMALL: Stop installing reiserfsprogs

- etc/grml/fai/config/package_config/GRML_SMALL
No changes to the software set, just introduce the same groups as in the GRML_FULL set.
> GRML_SMALL: apply same groups as in GRML_FULL

- etc/grml/fai/config/files/etc/apt/sources.list.d/debian.list/DEBIAN_TESTING
Both work, but the new URL is easier cacheable, and works with apt-cacher-ng.
> DEBIAN_TESTING: correct security.debian.org URL

- grml-live
- templates/boot/grub/%SHORT_NAME%_default.cfg
- templates/boot/grub/%SHORT_NAME%_options.cfg
- templates/boot/grub/addons.cfg
- templates/boot/grub/grub.cfg
- templates/boot/grub/header.cfg
The default menu entry now just reads "<grml-name> <version>", so for example "grml-small-arm64 2024.12". The additional options are in a menu entry just titled " -> Options".
To allow for removing the name/version for the options menu, grub.cfg now sorts the %SHORTNAME%_options.cfg always directly after the %SHORTNAME%_default.cfg.
Use unicode.pf2 to allow for Unicode characters in the Options and Addons menu entries.
Will need a trivial rebase after #181 is merged.
Closes #175.
> grub: retitle grml boot menu entries

- grml-live
Debian buster has xorriso 1.5.0-1, so this check is long obsolete.
> grml-live: remove xorriso version check

- grml-live
Skip the prompt with -F, but always print the configuration.
> grml-live: always print requested configuration

- etc/grml/fai/config/package_config/GRMLBASE
- grml-live
- templates/boot/grub/addons.cfg
- templates/boot/grub/grub.cfg
Moves non-addon entries out of addons.cfg. With NO_ADDONS=1, addons.cfg is deleted, but those entries should still exist.
Then we set NO_ADDONS=1 early, if the addons directory is missing, instead of just complaining later.
With this, the same code path as for NO_ADDONS=1 is executed, when the addons directory is missing. This causes addons.cfg to be (correctly!) deleted.
Also add NO_ADDONS=1 state to grml-live configuration output, and always show the requested configuration, even if -F is given.
---
Additionally, this removes syslinux/isolinux/pxelinux from the arm64 builds. These tools are x86-only, and as such are only dead weight on arm64. Bonus effect: the resulting ISO is understood by macOS once again.
> Improve addons-absent code flow, drop syslinux on arm64

- etc/grml/fai/config/scripts/GRMLBASE/45-grub-images
Fixes: 5eb2286046098c77cf43d45d18e023eda2aa4c9c
Error:
```
=====   shell: GRMLBASE/45-grub-images   =====
grub-mkimage: error: cannot open `/usr/lib/grub/x86_64-efi/efi_gop efi_uga.mod': No such file or directory.
GRMLBASE/45-grub-images FAILED with exit code 1.
```
> 45-grub-images: fix quoting

- grml-live
Fix embarrassing typo causing build-only to fail like this:
```
...
Volume id    : 'grml-small-arm64 d20241209b151'
xorriso : UPDATE :       2 files restored ( 392.3m) in 1 seconds , 296.9xD
xorriso : UPDATE :       3 files restored ( 394.1m) in 1 seconds = 297.0xD
Extracted from ISO image: file '/live'='/tmp/tmp.qcRmTPEtzH/live'
[!] Error: Could not find any *.squashfs files on the ISO
```
> grml-live: fix build only mode

- grml-live
The exclusion does not work today. /boot/ inside the squashfs always has vmlinuz* and initrd.img* files. IMO if the exclude would work, it would break build-only mode later.
A resulting grml-small build-only ISO does not change in size.
> grml-live: remove GRML_SMALL exclude of vmlinuz, initrd.img

- build-driver/build.py
Necessary for running in rootless podman, where the default /tmp has lots of restrictions. Not relevant for our CI, but for my local test builds.
> build-driver: honor TMPDIR

- grml-live
Ignore all extended attributes from files in chroot when adding them to the squashfs.
This avoids:
1) leaking containerization supplied selinux attributes into the squashfs, which can be seen when building in podman, and in docker.
2) prevents unpacking errors in a later build-only step in containers not supporting xattrs. Can also be seen in podman.
On a normal machine and also on a normal (booted) Grml system, the only things having xattrs are:
```
file: var/log/journal
system.posix_acl_access
system.posix_acl_default
file: var/log/journal/1e77092b16004314a93d779757d513ac
system.posix_acl_access
system.posix_acl_default
```
Both of these are apparently applied by systemd/journald during boot, even if the filesystem does not have them.
> grml-live: strip xattrs in squashfs

- .github/workflows/test-build.yml
- test/gha-build-iso.sh
Add an invocation of grml-live to the test-build GitHub Actions workflow. The results are collected as artifacts.
I consider this an initial start of having some form of end-to-end test for grml-live.
What I don't want here is to "test" Debian itself. For this reason, the test setup creates a minimal flavour/class. But at least GRMLBASE must work.
> GHA: run grml-live in test-build workflow

- etc/grml/fai/config/scripts/GRMLBASE/45-grub-images
Trivial issue, introduced in e1a55042bafe00328b59bd9e080b443de7a40097
> GRMLBASE/45-grub-images: fix moddep.lst name in message

- etc/grml/fai/config/scripts/GRMLBASE/15-initsetup
ldconfig.service is mostly useful if the OS image can change its composition during boot. This is not the case for us.
As ldconfig.service can be quite slow, lets mask it.
Closes: grml/grml-live#200
> GRMLBASE/15-initsetup: mask ldconfig.service

- .github/workflows/test-build.yml
- test/gha-build-iso.sh
Extend test-build GitHub Actions workflow to run release mode build after creating a daily ISO. The release mode build is done twice, to ensure a) it can work from a daily ISO and b) it can work from a release (candidate) ISO.
> GHA: test build-only/release mode

- build-driver/build.py
Apparently I dropped adding the SOURCES class in a refactor/cleanup. Readd that.
> build-driver: fix SOURCES class gone missing

- grml-live
Makes the netboot package name depend on the ISO_NAME, by appending `-netboot.tar` (obv. stripping `.iso` first).
Fixes #205
> netboot package: use ISO_NAME-netboot.tar as output name (without .iso)

- etc/grml/fai/config/package_config/GRML_FULL
- etc/grml/fai/config/package_config/GRML_SMALL
The current OpenSSH version has dropped support for DSA keys. Users might find them in a situation where they still need DSA keys when they're running our Live CD, so lets provide openssh-client-ssh1 too. At least for a while, until either openssh-client-ssh1 becomes unsupportable or enough time has passed.
Also drop "ssh" from GRML_FULL, as GRMLBASE already has openssh-client and openssh-server.
Adds about 1.5MB installed size.
> SW: Install openssh-client-ssh1 for DSA-keyed servers

- build-driver/build.py
This was necessary before the code got moved to grml-live.git. It is now done in the gitlab ci job configuration.
> build-driver: remove unused get_grml_live function

- grml-live
Even with the smaller grml-small builds we end up with >1k source files inside the grml_sources directory. We don't want this for our daily builds. But also for our release builds we prefer to have one single build artifact which we can pass within our build pipeline.
Example:
```
```
Then we generate grml_2024.12-1-sources.tar + grml_2024.12-1-sources.tar.sha256 inside build directory /home/mika/build/grml-live-2024-12/.
Underlying command line for this then being:
```
tar -C /home/mika/build/grml-live-2024-12 -cf /home/mika/build/grml-live-2024-12/grml_2024.12-1-sources.tar grml_sources
```
FTR: as of commit 87524f9aa1efb2327f45feef9028461b683ffec5 we no longer re-use the source directory with grml-live runs, so we could even remove the grml_sources directory automatically, but we …
> Generate source package tarball when using SOURCES class

- etc/grml/fai/config/grml/squashfs-excludes
The resulting device nodes are problematic when unpacking inside unprivileged podman containers, and the livecd does not need them to work.
> Do not add /dev to squashfs

- etc/grml/fai/config/hooks/updatebase.GRMLBASE
- etc/grml/fai/config/scripts/GRMLBASE/20-sudo
- etc/grml/fai/config/scripts/GRMLBASE/25-locales
- etc/grml/fai/config/scripts/GRMLBASE/26-console-setup
- etc/grml/fai/config/scripts/GRMLBASE/30-fstab
- etc/grml/fai/config/scripts/GRMLBASE/31-motd
- etc/grml/fai/config/scripts/GRMLBASE/34-hosts
- etc/grml/fai/config/scripts/GRMLBASE/35-network
- etc/grml/fai/config/scripts/GRMLBASE/39-modprobe
- etc/grml/fai/config/scripts/GRMLBASE/41-modules
- etc/grml/fai/config/scripts/GRMLBASE/42-branding
- etc/grml/fai/config/scripts/GRMLBASE/43-rsyslog
- etc/grml/fai/config/scripts/GRMLBASE/51-cloud-init
- etc/grml/fai/config/scripts/GRMLBASE/80-initramfs
- etc/grml/fai/config/scripts/GRML_FULL/01-firefox
When running grml-live from within the git repository that was cloned by a user other than root, the files installed by FAI's fcopy have wrong/unexpected permissions.
For example:
```
| # stat /home/mika/build/grml-live-2024-12/grml_chroot/etc/rsyslog.conf
|   File: /home/mika/build/grml-live-2024-12/grml_chroot/etc/rsyslog.conf
|   Size: 1106            Blocks: 8          IO Block: 4096   regular file
| Device: 253,2   Inode: 4472261     Links: 1
| Access: (0644/-rw-r--r--)  Uid: ( 1000/    mika)   Gid: ( 1000/    mika)
| Access: 2024-12-18 15:39:59.477471695 +0100
| Modify: 2023-08-07 13:32:24.000000000 +0200
| Change: 2024-12-10 17:02:16.177262515 +0100
|  Birth: 2024-12-10 17:02:16.177262515 +0100
```
fcopy provides the following options:
```
| % fcopy -h
| fcopy, copy files using …
```
> Ensure files are copied with fcopy into chroot with expected permissions

- build-driver/build.py
Fetch sources.tar from base build, and copy and rename it for the resulting release build. Automatically skip the SOURCES class, as grml-live cannot unpack/update the sources.tar yet.
> build-driver: copy sources.tar in release mode

- grml-live
We redesigned grml-live-grml in
https://github.com/grml/grml-live-grml/pull/11 to ship architecture specific boot addon templates. This should simplify our life by being able to ship files under identical names on all supported architectures.
> Introduce architecture specific boot addon templates

- etc/grml/grml-live.conf
- grml-live
- templates/boot/grub/addons.cfg
We no longer ship bsd4grml via grml-live-grml (see https://github.com/grml/grml-live-grml/pull/11), and bsd4grml is so well hidden inside Grml boot, that 2 out of 3 core devs didn't even find it. 8-)
(FTR: in BIOS boot with isolinux/syslinux, one needs to select the "Run Bootloader Grub2" addon sub menu entry, and then under Addons -> "MirOS bsd4grml (via loopback)" needs to be selected, related see commit 438804cfdd3a4c29dd9e9ffd9cedeb35f15bc6c6).
As this boot option was supported on legacy boot (as in BIOS / Non-UEFI boot) only anyway, let's stop supporting it.
See https://github.com/grml/grml/issues/211
> Drop support for bsd4grml / NO_ADDONS_BSD4GRML

- build-driver/build.py
Avoids exploding the CI artifact zip size, and thus failing builds.
> build-driver: delete grml_sources in results directory

- etc/grml/fai/config/package_config/DEBIAN_TESTING
- etc/grml/fai/config/package_config/DEBIAN_TRIXIE
- etc/grml/fai/config/package_config/DEBIAN_UNSTABLE
- etc/grml/fai/config/scripts/GRMLBASE/45-grub-images
- grml-live
We dropped support for i386, though there are 32bit EFI systems with 64bit CPUs out in the wild, so let's support UEFI 32bit boot on amd64.
Verified with `/usr/share/OVMF/OVMF32_CODE_4M.fd` from ovmf-ia32 (v2024.11-2) and qemu, running:
```
% qemu-system-amd64 -m 2048 -M pc -cdrom /path/to/grml_isos/grml_0.42iso -drive if=pflash,format=raw,unit=0,file.filename=/usr/share/OVMF/OVMF32_CODE_4M.fd,file.locking=off,readonly=on
```
Launch boot UEFI interactive shell there and verified that this works:
```
fs0:
cd efi/boot
bootia32.efi
```
This shows the Grml boot menu as expected, whereas executing bootx64.efi fails (as we're running within a 32bit EFI environment), also as expected.
NOTE: We already ship the grub-efi-ia32-bin package on AMD64 already for support within …
> Support UEFI 32bit boot on amd64

- grml-live
In commit 87524f9aa1efb2327f45feef9028461b683ffec5 we adjusted the grml_sources handling, as bind mounts are not allowed in (unprivileged) docker.
Now when running grml-live with SOURCES class enabled multiple times in a row (e.g. via grml-live's `-b` or `-u` options), one ends up with the $OUTPUT/grml_sources *and* $OUTPUT/grml_chroot/grml-live/grml_sources directories. grml-live then complains:
```
mv: cannot overwrite '$OUTPUT/grml_sources': Directory not empty
rmdir: failed to remove '$OUTPUT/grml_chroot/grml-live': Directory not empty
```
As of commit 8b0a6fafc1003d1bac28c6c26c95bd1869d5d74d we generate a source package tarball when using the SOURCES class, so one might want to remove the "${OUTPUT}/grml_sources" directory anyway (similar to what we're doing in commit …
> Fix logic around grml_sources handling no longer being bind-mounted

- etc/grml/fai/config/package_config/GRMLBASE
Once again grml2usb can be installed on all architectures.
> SW: install grml2usb on arm64, too

- templates/GRML/grml-cheatcodes.txt
- templates/boot/grub/%SHORT_NAME%_options.cfg
- templates/boot/isolinux/hidden.cfg
- updated description of the Isolinux bootprompt options to match actual behavior:
- floppy uses syslinux' `localboot 0x0` command
- hd .. hd3 use syslinux' `localboot 0x80` to `localboot 0x83` command
- hd0 / fd0 use syslinux' chain.c32 COM module to chainload the according MBR
- debug does not provide any shells during the boot process.
- add links to syslinux documentation (esp. for localboot + chain.c32)
- grml debug [...] was dropped as it was not working under systemd as intended, see: grml/grml#3 + grml/grml-autoconfig@f9648a3
- debug, nofb, nokms + serial were defined in hidden.cfg + grml.cfg but grml.cfg takes precedence.
- removed `video=ofonly` from all boot parameters as it does nothing. Quoting: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1377878/comments/39
> Where …
> Update Grml cheatcodes + clean up isolinux bootprompt options

- build-driver/build.py
Most importantly this deletes `grml_sources` before uploading to the daily host.
Saves us disk space and upload time.
The build driver is slightly more internally consistent now, too.
> build-driver: handle sources before upload_daily

- build-driver/build.py
Necessary for the CI jobs so a single test/collate step can collect artifacts from all build steps.
> build-driver: rename grml_logs to a per-job unique name

- etc/grml/fai/config/scripts/GRMLBASE/95-package-information
The file grew in size over time, not at about 5MB uncompressed.
> Reduce size of nonfree-licenses.txt by gzip-compressing it

- etc/grml/fai/config/scripts/GRMLBASE/95-package-information
We ship aptitude only via GRML_SMALL but not on GRML_SMALL, therefore the nonfree-licenses.txt file is missing on all grml-small flavours.
So if aptitude is not available, fall back to `apt-cache show` to get list of non-free packages.
Related changes:
* simplify code flow logic (no need for else within if ... exit)
* fix code indention
* run script under pipefail to properly fail on errors
> scripts/GRMLBASE/95-package-information: get non-free info also without aptitude

- build-driver/upload-daily.py
The CI jobs rely on a certain layout, but latest/ does not fulfill it. Mimic the minimum, specifically: grml_isos must exist, and *-sources.tar must exist.
> build-driver: create compatibly layout in /latest/

- build-driver/build.py
- test/gha-build-iso.sh
Necessary as during the 2024.12 release the URL to the metadata files has changed.
> build-driver: update URL to latest release dpkg.list

- etc/grml/fai/config/files/etc/systemd/system/getty@tty1.service.d/override.conf/GRMLBASE
- etc/grml/fai/config/files/etc/systemd/system/getty@tty2.service.d/override.conf/GRMLBASE
- etc/grml/fai/config/files/etc/systemd/system/getty@tty3.service.d/override.conf/GRMLBASE
- etc/grml/fai/config/files/etc/systemd/system/getty@tty4.service.d/override.conf/GRMLBASE
Let systemd set the current working directory for tty1-tty4 to the users (either root or $USERNAME) home directory. Then we can remove hacks in zshenv/zshrc.
> ttys: set WorkingDirectory to $HOME

- etc/grml/fai/config/scripts/GRMLBASE/26-console-setup
Previously console-setup would on startup find and copy the keymap and console font into /etc/console-setup.
This moves this caching step to grml-live execution time, and thus out of the (first) boot.
Files affected:
* /etc/console-setup/cached_UTF-8_del.kmap.gz
* /etc/console-setup/cached_Uni3-Terminus16.psf.gz
* /etc/console-setup/cached_setup_font.sh
* /etc/console-setup/cached_setup_keyboard.sh
* /etc/console-setup/cached_setup_terminal.sh
> console-setup: create setupcon cache

- debian/grml-live.maintscript
- docs/grml-live.txt
- etc/grml/fai/config/files/etc/apt/sources.list.d/debian.list/DEBIAN_BOOKWORM
- etc/grml/fai/config/files/etc/apt/sources.list.d/debian.list/DEBIAN_BULLSEYE
- etc/grml/fai/config/files/etc/apt/sources.list.d/debian.list/DEBIAN_ETCH
- etc/grml/fai/config/files/etc/apt/sources.list.d/debian.list/DEBIAN_STABLE
- etc/grml/fai/config/files/etc/apt/sources.list.d/debian.list/DEBIAN_TESTING
- etc/grml/fai/config/files/etc/apt/sources.list.d/debian.list/DEBIAN_TRIXIE
- etc/grml/fai/config/files/etc/apt/sources.list.d/debian.list/DEBIAN_UNSTABLE
- etc/grml/fai/config/hooks/updatebase.GRMLBASE
- etc/grml/fai/config/scripts/GRMLBASE/33-aptsetup
- etc/grml/grml-live.conf
- grml-live
Both point to the same CDN nowadays, but the deb.debian.org name is more popular with automatic caching redirects et al.
While at it, drop the apt sources.list file for `DEBIAN_ETCH`.
> Switch from ftp.debian.org to deb.debian.org

- etc/grml/fai/config/scripts/GRMLBASE/49-sshd
Should be more stable, and easier to understand.
> 49-sshd: create dropin file instead of using sed

- config/files/etc/fstab/GRMLBASE
These example entries are mounted by systemd. Avoid redefining them over systemds internal definition.
Mirrors https://github.com/grml/grml-udev-config/pull/4
Alternatively we could just drop the file from grml-live completely? grml-udev-config will write it anyway (I think).
> etc/fstab: drop examples handled by systemd

- build-driver/build.py
- build-driver/generate-changes-list.py
1) Sort debian package names in `changes-last*.txt`
2) Fix a0e5bbbe5b4f3024323d2c856c25d26e5fefe77a which broke selecting dpkg.list for the correct flavor (currently always the file from `full` is used)
> build: sort debian changes, fix flavor

- grml-live
Debian oldoldstable already has syslinux `3:6.04~git20190206.bf6db5b4+dfsg1-1`, so this check should have become unnecessary.
> grml-live: remove check for syslinux from before oldoldstable

- config/scripts/GRMLBASE/21-usersetup
adduser is supposed to be idempotent; with -q it also does not log a warning when the user is already in the given group.
> GRMLBASE/21-usersetup: remove grep of group file

- grml-live
Unnecessary since 530ec9ff0ac712bc4dab45ea820725d863154c59.
> Stop installing memdisk

- config/hooks/instsoft.GRMLBASE
FAI before 6.2.3 diverts /sbin/init. Previously we got away with this by having systemd-sysv installed into the basefiles and then never upgrading it. But since c84d711d215eb62c1e4712f5280630000804a544 systemd-sysv gets installed in instsoft, triggering the broken behaviour.
Fixes: c84d711d215eb62c1e4712f5280630000804a544
> Workaround /sbin/init vanishing, Debian bug #1056151

- templates/boot/grub/addons.cfg
Because we do not have any cpu selection logic in the isolinux boot path, grml-live *always* installs the BIOS-mode memtest86+ binaries as /boot/addons/memtest.
Thus, the check for /boot/addons/memtest86+x64.bin and /boot/addons/memtest86+ia32.bin can never have worked. Drop it.
On `grml-small-daily20241223build179testing-amd64.iso`, only `Memory test (memtest86+)` is visible in BIOS-grub.
> grub: remove nonfunctional memtest86 bios-mode selection

- build-driver/build.py
Make mmdebstrap more verbose, and install netbase so apt can resolve SRV records for the large package download phase. This works around this apt bug: http://bugs.debian.org/1092164
> build-driver improvements

- config/hooks/instsoft.GRMLBASE
I think this was not useful for the last 10 years or so, and at least from trixie on makedev is completely gone.
> Stop providing /dev/MAKEDEV

- config/files/etc/apt/apt.conf.d/15grml-live/GRMLBASE
http://trac.lighttpd.net/trac/ticket/657 was apparently fixed 15 years ago.
> Remove workaround for lighty issue from 15years ago

- config/scripts/RELEASE/98-clean-chroot
This was introduced in 0c469a66c1d77ef2aff158145bb3ccec02dc361a together with code in grml-live.  In 4152229391fd4af0ab4b88408a3efff2e7f52f37 I removed the check for the touch-file.
Clean this up.
> Remove obsolete touch /etc/grml_fai_release

- config/scripts/GRMLBASE/98-clean-chroot
This decides between resolvconf older or newer 1.80. Debian oldstable (bullseye) already has 1.87, so this is obsolete from our PoV.
> Remove version detection of old resolvconf

- config/hooks/instsoft.GRMLBASE
- config/hooks/updatebase.GRMLBASE
- config/scripts/GRMLBASE/45-grub-images
- grml-live
No immediate benefit except a bit of cleanup.
Will become necessary on something I'm working on 😊
> grml-live: stop passing env vars to fai, make fai overridable

- grml-live
Fixes: 81efbabe7211084b9b75803c7040b929c15fbcce dbfb6371f64363805a1a96b628d626e34372839b
All `*.c32` files went missing in the ISO because the path calculation is wrong.
> Fix missing isolinux files

- config/scripts/GRMLBASE/18-timesetup
tzdata 2024b-6 stops creating /etc/timezone, so we should not create it either.
> Update /etc/timezone only if it exists

- config/hooks/instsoft.ZFS
Necessary for building for arm64.
> ZFS: derive linux package names from primary Debian architecture

- usr/share/zsh/vendor-completions/_grml-live
* automatically retrieve the snapshot-dates in the last 6 months for the archive "debian" and only complete full days as you will have a lot to choose from with granuality of minute based snapshots
> zsh completion: wayback dates via /mr/timestamp

- usr/lib/grml-live/minifai
Instead use apt install again, which has the traditional solving behaviour.
Fixes: #281 
Relevant for GRML_FULL, which installs wireguard. wireguard Depends wireguard-modules. apt satisfy picks linux-image-rt-$arch to satisfy the virtual package wireguard-modules, ignoring linux-image-amd64 for this resolution.
> minifai: avoid using apt satisfy

- config/class/GRMLBASE.var
- config/scripts/GRMLBASE/18-timesetup
- templates/GRML/grml-cheatcodes.txt
Correctly create /etc/localtime as a symlink. Also stop dealing with /etc/adjtime, which does not exist anymore. Instead document RTC=UTC as default.
Remove GRMLBASE.var "UTC", and default TIMEZONE to Etc/UTC, to get the debconf variables correctly set.
Corresponding grml-autoconfig change: https://github.com/grml/grml-autoconfig/pull/30
> Fix timezone and RTC setup

- usr/lib/grml-live/minifai
In a daily build we saw this failure:
```
D: Running "/builds/grml/build-daily/grml-live/config/scripts/GRMLBASE/15-initsetup"
E: minifai fcopy: got no reply from server
Exception in thread Thread-1 (helper_socket_thread):
Traceback (most recent call last):
File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
self.run()
File "/usr/lib/python3.11/threading.py", line 975, in run
self._target(*self._args, **self._kwargs)
File "/builds/grml/build-daily/grml-live/usr/lib/grml-live/minifai", line 390, in helper_socket_thread
request_socket.send(f"{rc!s}\n".encode())
BrokenPipeError: [Errno 32] Broken pipe
D: fcopy recursive=True ignore_missing=True user='root' group='root' mode=420 paths=['etc/systemd']
E: Script /builds/grml/build-daily/grml-live/config/scripts/GRMLBASE/15-in …
```
> minifai: debug fcopy failure

- templates/GRML/grml-cheatcodes.txt
- templates/boot/isolinux/f4
We replaced "gmt" with "utc" some time ago, see: 65ee43c.
In the meanwhile we changed the timezone and localtime handling and dropped support for the bootoption "utc", as it is the default nowadays, see: grml/grml-autoconfig@e96da70 + grml/grml-live@34167e2f.
TZ defaults to UTC and the RTC defaults to be set to UTC.
Related: grml/grml-live#296
> isolinux: Drop bootoption "gmt"

- config/package_config/GRML_FULL
Now that we dropped gnupg as dependencty from the grml-keyring package, we need to make sure to have it available at least on GRML_FULL.
We might consider migrating to sq instead in the future, feedback welcome.
> SW: add gnupg to GRML_FULL

- config/package_config/GRML_FULL
- grml-live
Only supports the new filename scheme for EFI; for legacy boot nothing has changed.
> Follow ipxe 1.21.1+git20220113.fbbdc3926+dfsg-3 changes

- templates/GRML/grml-cheatcodes.txt
Booting a live system probably shouldn't trigger any microcode updates. The dis_ucode_ldr kernel parameter disables the microcode loader, see https://www.kernel.org/doc/html/latest/admin-guide/kernel-parameters.html and
https://wiki.debian.org/Microcode#Working_around_boot_problems_caused_by_microcode_updates
> Document kernel option dis_ucode_ldr

- config/package_config/GRMLBASE
iwd seems to be required for support of wpa-enterprise networks. Given that we consider network connectivity as essential and already ship the wpasupplicant package in GRMLBASE, and iwd only adds 2,717 kB of additional disk space (including its dependency libell0), let's also include it into our base software selection.
Closes: grml/grml#226
> SW: add iwd to GRMLBASE

- debian/grml-live.install
- etc/cruft/filters/grml-live
this could only be /etc/grml/grml-live.local but i don't think that i'm the only person who keeps more configurations in there.
```
cb@obelix ~crpb/grml-live (git)-[cruft] % ls -1 /etc/grml/*local
/etc/grml/grml-bookworm-full.local
/etc/grml/grml-bookworm-small.local
/etc/grml/grml-sid-full.local
/etc/grml/grml-sid-small.local
/etc/grml/grml-trixie-full.local
/etc/grml/grml-trixie-small.local
/etc/grml/test-bookworm-small.local
/etc/grml/test-sid-small.local
/etc/grml/test-templ.local
/etc/grml/test-trixie-small.local
```
> etc/cruft/filters/grml-live: filter /etc/grml/*.local

- usr/share/zsh/vendor-completions/_grml-live
* jq needs to be installed, python3 most likely not. \o/
* and don't forget about curl...
> usr/share/zsh/vendor-completions/_grml-live: use python instead of jq

- scripts/migrate-to-minifai
Executing it converts our existing config/* from FAI layout (e.g. config/files/$FILENAME/$CLASS) into the new minifai layout (e.g. config/files/$CLASS/$FILENAME).
See https://github.com/grml/grml-live/issues/267
> Provide migration script migrate-to-minifai

- config/files/GRMLBASE/etc/systemd/system/ssh.service.d/keygen.conf
Apparently trixie's ssh.service got an ExecStartPre= line. Our override would apply *after* it, but that is too late.
Closes https://github.com/grml/grml/issues/228
> ssh.service: adapt for trixie

- usr/lib/grml-live/minifai
> fcopy: remove target files and symlinks before overwriting them

- config/hooks/GRMLBASE/instsoft
- config/scripts/GRMLBASE/80-initramfs
- config/scripts/GRMLBASE/98-clean-chroot
A normal build would run update-initramfs three times. This cuts it down to one run.
> Divert update-initramfs for performance 

- config/package_config/GRML_FULL
This package pulls in debian-ports-archive-keyring, though we aren't aware of any good reasons why we should ship those packages by default.
> SW: drop crosshurd from GRML_FULL

- config/files/GRMLBASE/etc/systemd/system-preset/10-grml.preset
- config/files/GRMLBASE/etc/systemd/system/avahi-ssh.service
- config/files/GRML_FULL/etc/systemd/system/avahi-daemon.service.d/override.conf
We want to announce the SSH service with Avahi.
The avahi-daemon is shipped in GRML_FULL but needs be enabled and a Avahi ssh service configuration file needs to be deployed.
The avahi-ssh.service deploys the SSH service config for Avahi when the SSH service is started. The service avahi-ssh.service needs to be enabled too.
To discover the SSH service in the local network the following command can be used:
```
avahi-browse -d local _ssh._tcp --resolve -t
```
Issue: grml/grml-live#73
> Announce SSH service with Avahi

- config/scripts/GRMLBASE/98-clean-chroot
When using plocate, we need to have /proc available, otherwise it fails hard and non-obvious with
`linkat: No such file or directory`
> GRMLBASE/98-clean-chroot: support plocate usage

- config/files/GRMLBASE/etc/grml/autoconfig
- config/files/GRMLBASE/usr/share/grml-autoconfig/autoconfig.functions
- config/files/GRMLBASE/usr/share/grml-autoconfig/grml-autoconfig
- templates/GRML/grml-cheatcodes.txt
The Debian brltty package installs an initramfs hook, which automatically
starts brltty, as long as a brltty.conf is available. Thus on GRML_FULL,
brltty is always started. It's also a lot earlier than grml-autoconfig
could do it.
Remove the grml-autoconfig code for brltty, as it does not add any value.
Supersedes #357.
> autoconfig: remove brltty start, done by initramfs

- config/scripts/GRMLBASE/03-get-sources
- usr/lib/grml-live/minifai
For testing deb.debian.org issues.
https://gitlab.grml.org/grml/build-daily/-/commit/eb5fdd1a183f8ef404c49f8d7b2fe11ba0c89767 is too fiddly.
/cc @pkern
> Add Debug::Acquire::http=true to apt if GRML_LIVE_DEBUG_APT is set

- usr/lib/grml-live/minifai
Ensures all sources are available, instead of failing later because some package is unavailable.
Closes: grml/grml-live#332
> minifai: run apt-get update step with --error-on=any

- scripts/generate_netboot_package.sh
- templates/boot/grub/%SHORT_NAME%_default.cfg
- templates/boot/grub/%SHORT_NAME%_options.cfg
- templates/boot/grub/netboot.cfg
- templates/boot/isolinux/default.cfg
- templates/boot/isolinux/grml.cfg
- templates/boot/isolinux/hidden.cfg
- templates/boot/isolinux/netboot.cfg
We have not managed to complete this task since 2019. Enable it now, and when something breaks, people can tell us.
Closes: grml/grml#127
> Enable predictable network device names

- usr/lib/grml-live/minifai
there is no bonus in using "apt" over "apt-get" with the command "install" other than it still spews out warning about it's cli interface.
> minifai: apt disable-script-warning

- grml-live
Useful for platforms using u-boot to boot.
We will do this just based on the existence of /boot/dtbs in the chroots. Then the chroot (packages, hooks, scripts) are in control of triggering this. We do not need an arbitrary arch-restriction.
Closes: grml/grml-live#336
> grml-live: copy /boot/dtbs out

- build-driver/build.py
- config/package_config/IGNORE
Was useful only in the old Jenkins CI setup for grml.org builds. We no longer use that, so the class has outlived its usefulness.
> Drop IGNORE class

- docs/grml-live.8.txt
- etc/grml/grml-live.conf
- grml-live
I intend to make changes later to how and where these variables are setup and passing all of them through to the python tools is annoying.
I can see how it was useful to move individual output directories in the past, but I'm counting on computers being fast and big enough today.
For our own builds, build-driver lets grml-live default the vars and then moves whatever it needs.
> Deprecate setting individual *_OUTPUT vars 

- docs/grml-live.8.txt
- etc/grml/grml-live.conf
- grml-live
Instead support a new `BOOTSTRAP_MIRROR` variable, which has *just* the mirror URL.
Judging by an example in the docs, since introducing minifai, we were not fully compatible with the old syntax.
Ideally minifai would determine the mirror URL from the class config, but that needs some form of marking one of the sources files as the bootstrap one. Ideas welcome.
> Deprecate FAI_DEBOOTSTRAP

- config/media-scripts/GRMLBASE/50-addons
On FULL and AMD64 builds, /boot/addons already exists before 50-addons runs. `mv` then fails as it does not "merge" directories.
Use `cp -r` and `rm -r` instead to get the "merge" behaviour.
Maybe it would be better to extend fcopy/copy-media-files to allow a destination path.
Fix from #402 was not complete.
> GRMLBASE/50-addons: fix merging addons directory

- grml-live
Not necessary given we use mmdebstrap.
> grml-live: remove "sid" hack for debootstrap

- .github/workflows/test-build.yml
- config/bootstrap-keyring/DEBIAN_FORKY
- config/files/DEBIAN_FORKY/etc/apt/sources.list.d/debian.sources
- config/package_config/DEBIAN_FORKY
> Introducing forky the spork.

- config/package_config/GRML_FULL
- config/package_config/GRML_SMALL
tio is a simple TTY terminal I/O application, requires ~250kB on grml-full and 829 kB (with liblua5.4-0) on grml-small.
Thanks: Martin Karresand for the suggestion
> SW: add tio to GRML_SMALL + GRML_FULL

- config/scripts/GRMLBASE/25-locales
Follow Debian glibc 2.42-1, see Debian bug #1095101
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1095101
> Stop symlinking /etc/locale.alias
